---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by CriticalRR.
--- Copyright (c) CriticalRR - All Rights Reserved
--- DateTime: 06/04/2023 11:43
---

fx_version "cerulean"
game "gta5"
lua54 "yes"

name 'fivem-rainbowvehicle'
author 'CriticalRR'
contact 'CriticalR#0563'
repository 'https://github.com/CriticalRR/fivem-rainbowvehicle'
discord 'https://discord.gg/kcgKxtHgCf'
description 'This script for FiveM allows your players to give a dynamic effect to your vehicle by changing the color, neon lights and headlights every second on your server.'

client_scripts {
    "client/cl_rainbowvehicle.lua"
}
